version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - sm-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: smpostgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: smtest
    ports:
      - "5432:5432"
    networks:
      - sm-network
#    volumes:
#      - postgres-sm-data:/var/lib/postgresql/data

networks:
  sm-network:
    driver: bridge

#volumes:
#    postgres-sm-data: