spring.application.name=deploy-poc

server.port=8080

# Database connection
spring.datasource.url=jdbc:postgresql://postgres:5432/smtest
spring.datasource.username=smpostgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: JPA/Hibernate settings (if using JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

